//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuTra
    {
        public int MaCTPT { get; set; }
        public int MaPhieuTra { get; set; }
        public Nullable<int> MaSP { get; set; }
        public int SoLuong { get; set; }
    
        public virtual PhieuTra PhieuTra { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
