//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.PhieuTras = new HashSet<PhieuTra>();
        }
    
        public int MaDH { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public decimal TongTien { get; set; }
        public string TrangThai { get; set; }
        public string DiaChiGiao { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public decimal PhiShip { get; set; }
        public string DienThoaiGiao { get; set; }
        public string NguoiNhan { get; set; }
        public string MaVanDon { get; set; }
        public string DonViVanChuyen { get; set; }
        public string LyDoHuy { get; set; }
        public string GhiChu_Admin { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<decimal> TongThanhToan { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ICollection<PhieuTra> PhieuTras { get; set; }
    }
}
