//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTra
    {
        public PhieuTra()
        {
            this.ChiTietPhieuTras = new HashSet<ChiTietPhieuTra>();
        }
    
        public int MaPhieuTra { get; set; }
        public Nullable<int> MaDH { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string LyDo { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<ChiTietPhieuTra> ChiTietPhieuTras { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
